# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        touch .env
        echo CI_APP_PORT = ${{ secrets.CI_APP_PORT }} >> .env
        echo CI_DB_HOST = ${{ secrets.CI_DB_HOST }} >> .env
        echo CI_DB_PORT = ${{ secrets.CI_DB_PORT }} >> .env
        echo CI_DB_NAME = ${{ secrets.CI_DB_NAME }} >> .env
        echo CI_API_VERSION = ${{ secrets.CI_API_VERSION }} >> .env
        echo MYSQL_DB_HOST = ${{ secrets.MYSQL_DB_HOST }} >> .env
        echo MYSQL_USER = ${{ secrets.MYSQL_USER }} >> .env
        echo MYSQL_PASSWORD = ${{ secrets.MYSQL_PASSWORD }} >> .env
        echo MYSQL_DATABASE = ${{ secrets.MYSQL_DATABASE }} >> .env
    - run: npm ci 
    - run: npm run ci
     
